layout: sidebar
style: light
# style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  show_language: true
  show_stargazers_count: false
  show_forks_count: false
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    # forks: true
    projects:
      - kevinshi97.github.io
      - csc258
      - web-api-auth-examples
      - spotify-web
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

social_media: 
  github: kevinshi97
  linkedin: im-kevin-shi
  # email: kevins.shi@mail.utoronto.ca
  email: kevinsshi97@gmail.com
  resume: kevin-shi-resume.pdf

topics:
  - name: React
    web_url: https://github.com/topics/react
    image_url: /assets/images/react-logo.png

  - name: Electron
    web_url: https://github.com/topics/electron
    image_url: /assets/images/electron-logo.png

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: /assets/images/machine-learning-logo.png

publications:
  - name: Surprisingly Popular Voting Recovers Rankings, Surprisingly! (IJCAI-21)
    web_url: https://arxiv.org/abs/2105.09386
    pdf: spvoting.pdf